packages/dbml-homepage/deploy.sh, packages/dbml-homepage/docs/.vuepress/config.js, packages/dbml-homepage/docs/.vuepress/secret.js, packages/dbml-homepage/package.json, packages/dbml-homepage/yarn.lock
* Add ga default config of vuepress.
* Use vuepress plugin for google Analytics.
https://app.asana.com/0/1125458388096768/1135773918803106/f
=> set ga option and use vuepress google Analytics plugin

packages/dbml-core/__tests__/parser/dbml-parse/input/comment.in.dbml, packages/dbml-core/__tests__/parser/dbml-parse/output/comment.out.json, packages/dbml-core/__tests__/parser/mysql-parse/input/comment.in.sql, packages/dbml-core/__tests__/parser/mysql-parse/output/comment.out.json, packages/dbml-core/__tests__/schema-exporter/dbml-exporter/input/comment_tables.in.json, packages/dbml-core/__tests__/schema-exporter/dbml-exporter/output/comment_tables.out.dbml, packages/dbml-core/__tests__/schema-exporter/mysql-exporter/input/comment_tables.in.json, packages/dbml-core/__tests__/schema-exporter/mysql-exporter/output/comment_tables.out.sql, packages/dbml-core/__tests__/schema-exporter/postgres-exporter/input/comment_tables.in.json, packages/dbml-core/__tests__/schema-exporter/postgres-exporter/output/comment_tables.out.sql, packages/dbml-core/src/export/DbmlExporter.js, packages/dbml-core/src/export/Exporter.js, packages/dbml-core/src/export/MysqlExporter.js, packages/dbml-core/src/export/PostgresExporter.js, packages/dbml-core/src/parse/mysql/parser.pegjs, packages/dbml-core/src/parse/mysqlParser.js
=> Support import/export comment syntax for dbml, mysql and postgres

packages/dbml-core/src/export/JsonExporter.js
Make JSON produced by JsonExporter indented (width=2).
=> Indent JSON generated by JsonExporter

packages/dbml-core/src/parse/schemarb/parser.pegjs, packages/dbml-core/src/parse/schemarbParser.js
=> Feature: Referential actions for ActiveRecord Rails

packages/dbml-core/src/export/DbmlExporter.js
Fixed a simple syntax error
This is related to issue [#55 ](url)
packages/dbml-core/src/export/DbmlExporter.js
=> Fixed DBML one-to-one relation exporting bug 

packages/dbml-core/__tests__/parser/dbml-parse/input/array_type.in.dbml, packages/dbml-core/__tests__/parser/dbml-parse/output/array_type.out.json, packages/dbml-core/src/parse/dbml/parser.pegjs, packages/dbml-core/src/parse/dbmlParser.js
* Parsing array type for dbml
Example:
```
Table tictactoe {
squares integer[3][3]
}
```
#46 
=> Parsing array type for dbml

packages/dbml-core/__tests__/parser/dbml-parse/input/comment.in.dbml, packages/dbml-core/__tests__/parser/dbml-parse/output/comment.out.json, packages/dbml-core/src/parse/dbml/parser.pegjs, packages/dbml-core/src/parse/dbmlParser.js
=> Fix parsing index comment

dbml-homepage/docs/docs/README.md
Typo in docs
n/a
- ~[ ] Tests (integration test/unit test)~
- ~[ ] Integration Tests Passed~
- ~[ ] Code Review~
=> Fix typo in readme

packages/dbml-core/__tests__/model_structure/single_schema.js, packages/dbml-core/__tests__/model_structure/single_schema.json, packages/dbml-core/__tests__/parser/dbml-parse/input/index_tables.in.dbml, packages/dbml-core/__tests__/parser/dbml-parse/output/index_tables.out.json, packages/dbml-core/src/model_structure/indexes.js, packages/dbml-core/src/parse/dbml/parser.pegjs, packages/dbml-core/src/parse/dbmlParser.js, yarn.lock
* Parse index note for DBML
#82 
=> Parse index note for DBML

README.md
Added link to [PyDBML](https://github.com/Vanderhoof/PyDBML) into the Comunity Contributions section of README
https://github.com/holistics/dbml/issues/88
NONE
=> Add PyDBML to Comunity Contributions section of README

README.md, dbml-homepage/docs/home/README.md
Adds a link to FloorPlan; translating [Room](https://developer.android.com/topic/libraries/architecture/room) schemas (SQLite) to DBML.
N/A
=> Add FloorPlan to community contributions

dbml-homepage/docs/home/README.md
=> Add PyDBML to dbml homepage

README.md
Add Go DBML parser to README.md
=> Add golang parser to community contributes

packages/dbml-core/__tests__/parser/mysql-parse/input/general_schema.in.sql, packages/dbml-core/src/parse/mysql/parser.pegjs, packages/dbml-core/src/parse/mysqlParser.js
* Add field-level character set/charset support to MySQL parser.
https://github.com/holistics/dbml/issues/94
* "CHARACTER SET" or "CHARSET" recognised as MySQL field setting
=> Support field-level charset in MySQL parser

README.md
Adds a link to DbmlForDjango; translating Django models.py file to DBML.
N/A
Nothing
=> Add DbmlForDjango to Community Contributions

README.md
Updated README with a bullet under `Community contributions`
=> Add parseServerSchema2dbml to Community Contributions

lerna.json, packages/dbml-cli/README.md, packages/dbml-cli/package.json, packages/dbml-core/README.md
- Update @dbml/core in @dbml/cli
- Bump @dbml/cli version
- Update readme
Please check directly on the box once each of these is done
=> Update readme and bump version

packages/dbml-core/__tests__/importer/postgres_importer/input/general_schema.in.sql, packages/dbml-core/__tests__/importer/postgres_importer/output/general_schema.out.dbml, packages/dbml-core/src/parse/postgresParser.js, packages/dbml-core/src/parse/postgresql/Base_rules.pegjs
* Support parse time data type.
https://github.com/holistics/dbml/issues/78
=> Support parse time data type.

package.json, packages/dbml-core/package.json, packages/dbml-core/types/export/ModelExporter.d.ts, packages/dbml-core/types/export/index.d.ts, packages/dbml-core/types/import/index.d.ts, packages/dbml-core/types/index.d.ts, packages/dbml-core/types/model_structure/database.d.ts, packages/dbml-core/types/model_structure/dbState.d.ts, packages/dbml-core/types/model_structure/element.d.ts, packages/dbml-core/types/model_structure/endpoint.d.ts, packages/dbml-core/types/model_structure/enum.d.ts, packages/dbml-core/types/model_structure/enumValue.d.ts, packages/dbml-core/types/model_structure/field.d.ts, packages/dbml-core/types/model_structure/indexColumn.d.ts, packages/dbml-core/types/model_structure/indexes.d.ts, packages/dbml-core/types/model_structure/ref.d.ts, packages/dbml-core/types/model_structure/schema.d.ts, packages/dbml-core/types/model_structure/table.d.ts, packages/dbml-core/types/model_structure/tableGroup.d.ts, packages/dbml-core/types/parse/Parser.d.ts
* Add TypeScript versions of library files
* Add TypeScript type definition files for dbml-core
#62 
* Added TypeScript files to allow for generation of type definitions
* Generated type definitions and declared them in `package.json`
=> Add dbml-core type definitions

dbml-homepage/docs/docs/README.md
Update example for "create index with name" in **DBML - Full Syntax Docs / Index Definition**
https://github.com/holistics/dbml/issues/157
No code changes/things that have wide-effect
=> Update create index with name example

packages/dbml-core/__tests__/parser/dbml-parse/input/comment.in.dbml, packages/dbml-core/__tests__/parser/dbml-parse/output/comment.out.json, packages/dbml-core/src/parse/dbml/parser.pegjs, packages/dbml-core/src/parse/dbmlParser.js
Support multiline comment starting with /* and ending with  */
Example:
/\*
\* multi
\* line 
\* comment
\*/
=> Add multiline comment

dbml-homepage/docs/cli/README.md, dbml-homepage/docs/js-module/README.md
* Add npm package badges into doc pages
=> Doc: Add npm package badges

README.md, dbml-homepage/docs/home/README.md
* add dbml-parser for PHP by Butschster to community contributors list
* https://github.com/holistics/dbml/issues/201
=> add contributor butschster

dbml-homepage/docs/.vuepress/config.js, dbml-homepage/docs/home/README.md
* Add GitHub Stars shield
* Update home content
=> Update home page content

README.md, dbml-homepage/docs/home/README.md
* Add `Kacher: Laravel's Database Schemas to DBML` by Arsanandha Aphisitworachorch
* Reference: https://community.dbdiagram.io/t/laravel-database-to-dbml/1048
=> Add contributor Aphisitworachorch

dbml-homepage/docs/docs/README.md
* Remove old note about the unsupported many-to-many relationship
=> Update many-to-many relationship documentation

packages/dbml-core/__tests__/importer/importer.spec.js, packages/dbml-core/__tests__/importer/postgres_importer/input/timestampz_and_timetz_type.in.sql, packages/dbml-core/__tests__/importer/postgres_importer/output/timestampz_and_timetz_type.out.dbml, packages/dbml-core/src/parse/postgresParser.js, packages/dbml-core/src/parse/postgresql/Base_rules.pegjs
*Support timestamptz and timetz type for import postgresSQL
* https://github.com/holistics/dbml/issues/71
* Added `timestamptz` and `timetz` rules in `Base_rules.peg.js`
* Added test for `timestamptz` and `timetz` type
=> Support timestamptz and timetz type for import postgresSQL

CHANGELOG.md, lerna.json, packages/dbml-cli/package-lock.json, packages/dbml-cli/package.json, packages/dbml-core/package.json
=> release v2.4.3

packages/dbml-core/__tests__/importer/mysql_importer/input/create_table_using_index_type.in.sql, packages/dbml-core/__tests__/importer/mysql_importer/output/create_table_using_index_type.out.dbml, packages/dbml-core/src/parse/mysql/parser.pegjs, packages/dbml-core/src/parse/mysqlParser.js
* Fix missing space when creating index to use
```
KEY `user_id` (`user_id`) USING BTREE
```
https://github.com/holistics/dbml/issues/287
https://github.com/holistics/dbml/issues/251
* Added space in `mysql/paser.pegjs`
* Added test
=> Fix missing space when creating index

CHANGELOG.md, packages/dbml-cli/package-lock.json, packages/dbml-cli/package.json, packages/dbml-core/package.json
* Release version v2.4.4
* Added Change Log
* Update version in `package.json`
=> Release version v2.4.4

CHANGELOG.md, lerna.json, packages/dbml-cli/package-lock.json, packages/dbml-cli/package.json, packages/dbml-core/package.json
* Release version 2.5.0
- update changelog
- update `package.json`
=> Release version 2.5.0

dbml-homepage/docs/docs/README.md
Update DBML syntax docs.
Quick update.
- Remove 'coming soon' from header color example
- Update the Table Settings example
=> Update dbml syntax docs

CHANGELOG.md, lerna.json, packages/dbml-cli/package-lock.json, packages/dbml-cli/package.json, packages/dbml-core/package.json
* Release version 2.5.1
- update `package.json`
- update changelog
=> Release version 2.5.1

packages/dbml-cli/yarn.lock
* Upgrade @dbml/core version
- upgrade @dbml/core version
=> Upgrade @dbml/core version

CHANGELOG.md, lerna.json, packages/dbml-cli/package-lock.json, packages/dbml-cli/package.json, packages/dbml-core/package.json
* Release version 2.5.1
- update `package.json`
- update changelog
=> Release version 2.5.2

lerna.json
* Internal: add dependencies update label
- Add label `PR: Dependencies Update :robot:` to `lerna.json`
=> Internal: add dependencies update label

dbml-homepage/deploy.sh
=> Deployed to new domain dbml.dbdiagram.io

dbml-homepage/deploy.sh
* Update new domain for dbml homepage
=> Update new domain for dbml homepage

.github/workflows/build-docs.yml
* Add missing step in build-docs workflow
- Add missing `cd dbml-homepage` step
=> Add missing step in build-docs workflow

packages/dbml-cli/README.md
Include instructions for npx
* Including instructions in readme to use with npx
Documentations chane
=> [PR: Docs 📝] Update README.md

CONTRIBUTING.md, dbml-homepage/docs/home/README.md
* I noticed a small mistake with the contribution guidelines, and what better for a first contribution?
* "When you ready..." -> "When you're ready..."
Is this necessary for such a small change?
* None 
- [N/A] Tests (integration test/unit test)
- [N/A] Integration Tests Passed
- [N/A] Code Review
=> grammar fix

dbml-homepage/docs/docs/README.md
It follows the logic of this PR https://github.com/holistics/dbml/pull/352#issue-1659106202
none
Just a doc example update
=> docs: Update the example of table users in README.md

.github/workflows/bearer.yml
=> update fail on error bearer scan

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json
=> Release v2.6.0

dbml-homepage/docs/cli/README.md
=> Update CLI documentation about postgres-legacy option

packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/symbolIndex.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/symbolTable.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/symbols.ts
* Add SymbolTable to DBML parser to support the analyzer phase
* Previous PR #419 
* Next PR #422
=> 3. Parser symbol table

packages/dbml-core/src/parse/dbml/src/lib/analyzer/types.ts
* Add interfaces representing unresolved names to support binder.
* Previous PR: #420 
* Next PR: #423 
=> 4. UnresolvedName to support binder

packages/dbml-core/src/parse/dbml/src/compiler.ts, packages/dbml-core/src/parse/dbml/src/index.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/analyzer.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/factory.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/symbolTable.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/symbols.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/utils.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/custom.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/elementValidator.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/enum.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/indexes.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/note.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/project.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/ref.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/table.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/tableGroup.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/utils.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/validator.ts, packages/dbml-core/src/parse/dbml/src/lib/errors.ts, packages/dbml-core/src/parse/dbml/src/lib/parser/factory.ts, packages/dbml-core/src/parse/dbml/src/lib/parser/nodes.ts, packages/dbml-core/src/parse/dbml/src/lib/parser/parser.ts, packages/dbml-core/src/parse/dbml/src/lib/parser/utils.ts, packages/dbml-core/src/parse/dbml/src/lib/report.ts
* Rebuild Id system to be more robust.
* The parser & analyzer now keep an instance of a node & symbol factory to automatically assign next Ids on creation
=> 9. rebuild id system

packages/dbml-core/src/parse/dbml/src/services/suggestions/utils.ts
=> fix: bug in logical line logic

packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/utils.ts, packages/dbml-core/src/parse/dbml/src/lib/analyzer/utils.ts
=> Merge validator into alt-parser

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json
* Release version 2.6.1
- update `package.json`
- update changelog
=> Release version 2.6.1

dbml-homepage/docs/.vuepress/config.js, dbml-homepage/yarn.lock
* Add Holistics to dbx dropdown
* Update name for other dbx product in dropdown
=> Update dbx dropdown in homepage

dbml-homepage/docs/js-module/README.md, packages/dbml-core/src/parse/Parser.js
=> Trivial fixes

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump package version to v3.1.0
=> Release v3.1.0

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Release new packages to fix wrong file name casing in previous version
=> Release v3.1.1

dbml-homepage/docs/docs/README.md, packages/dbml-parse/src/lib/analyzer/validator/elementValidators/table.ts, packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts, packages/dbml-parse/tests/interpreter/input/column_caller_type.in.dbml, packages/dbml-parse/tests/interpreter/output/column_caller_type.out.json, packages/dbml-parse/tests/validator/input/column_caller_type.in.dbml, packages/dbml-parse/tests/validator/output/column_caller_type.out.json
* Support non-numerical argument in column type.
* Add test cases
* `TableValidator` column type validation logic.
* `TableInterpreter` column type interpretation logic.
=> feat: support strings and identifiers in column caller type

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
Release version 3.1.2
- Update changelog
- Update packages to version 3.1.2
=> Release v3.1.2

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump packages version to 3.1.3
=> Release v3.1.3

packages/dbml-core/__tests__/exporter/mssql_exporter/output/many_to_many_relationship.out.sql, packages/dbml-core/__tests__/exporter/mysql_exporter/input/1_to_1_relations.in.dbml, packages/dbml-core/__tests__/exporter/mysql_exporter/output/1_to_1_relations.out.sql, packages/dbml-core/__tests__/exporter/mysql_exporter/output/many_to_many_relationship.out.sql, packages/dbml-core/__tests__/exporter/postgres_exporter/output/many_to_many_relationship.out.sql, packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts, packages/dbml-parse/tests/interpreter/output/table_group.out.json, packages/dbml-parse/tests/old_tests/output/table_group.out.json
* 1-1 Foreign key endpoint swapped
=> fix: swap ref endpoints in inline_refs

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump packages version to v3.1.4
=> Release v3.1.4

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump packages version to v3.1.5
=> Release v3.1.5

packages/dbml-parse/src/lib/errors.ts, packages/dbml-parse/src/lib/interpreter/elementInterpreter/tableGroup.ts, packages/dbml-parse/src/lib/interpreter/interpreter.ts, packages/dbml-parse/src/lib/interpreter/types.ts, packages/dbml-parse/tests/interpreter/input/table_reappear_tablegroup.in.dbml, packages/dbml-parse/tests/interpreter/output/table_reappear_tablegroup.out.json
* Table reappearing in different TableGroups will raise an error
* `TableGroupInterpreter`
* Interpreter's `env`
=> Add check for table reappear in tablegroups

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump packages version to v3.1.6
=> Release v3.1.6

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump packages version to v3.1.7
=> Release v3.1.7

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump packages version to v3.1.8
=> Release v3.1.8

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump packages version to v3.2.0
=> Release v3.2.0

README.md, dbml-homepage/docs/home/README.md
* Add Nils Wende to community contributions
[Contribution: Java-based Parser #528](https://github.com/holistics/dbml/issues/528)
=> Add contributor dbml java

dbml-homepage/docs/docs/README.md, dbml-homepage/docs/home/README.md
Add the following things:
- Sticky Notes syntax guide
- A new community contribution
- Sticky Notes syntax guide.
- A new community contribution (SchemaToDbml from Ricardo Ribeiro).
=> Add Sticky Notes syntax guide and a new community contribution

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
Release v3.3.0
- Update changelog
- Update package.json to v3.3.0
=> Release v3.3.0

packages/dbml-parse/src/lib/interpreter/elementInterpreter/project.ts, packages/dbml-parse/tests/interpreter/output/project.out.json, packages/dbml-parse/tests/old_tests/output/project.out.json
* Fix an oversight: forget to normalize note content in projects.
=> fix: normalize note content in projects

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
Release v3.4.0
Update changelog and package.json for version 3.4.0
=> Release v3.4.0

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
Release v3.4.3
Update changelog for v3.4.3
=> Release v3.4.3

packages/dbml-core/src/index.js, packages/dbml-core/src/utils/version.js
Export @dbml/core version
Export @dbml/core version from package.json
=> Export @dbml/core version

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
Release v3.5.1
Update changelog and package.json files for version 3.5.1
=> Release v3.5.1

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Update packages version to v3.6.0
=> Release v3.6.0

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> Release v3.6.1

.gitignore, packages/dbml-parse/package.json, packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
* Fix this error:
* This is due to forgetting to add TokenPosition to columns in implicit composite indexes (one created by placing multiple `pk` on multiple columns):
* Add a typechecking step before building for dbml-parse so that the CI fails when there's a typecheck error.
=> fix: typescript-errors

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump packages version to v3.6.2
=> Release v3.6.2

yarn.lock
* Update missing change in yarn.lock
=> Update yarn.lock in v3.6.2

.github/workflows/test.yml, CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> Release v3.7.0

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
- Clean up build cache before starting build process
=> Release v3.7.1

dbml-homepage/docs/cli.md, dbml-homepage/docs/js-module.md
=> Docs - Add document for database connector

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
- Release table group note.
- Add dbml/connector package
=> Release v3.7.2

packages/dbml-core/package.json, packages/dbml-core/src/parse/Parser.js, packages/dbml-parse/src/services/suggestions/provider.ts, yarn.lock
* Fix a bug where monaco editor's suggestion not working properly.
* Remove `@tediousjs/connection-string` package in `dbml-core`
* Result
https://github.com/user-attachments/assets/cfac1abc-6c34-4100-8787-14239a62d3b9
=> Fix wrong suggestion behaviors for Table Groups

packages/dbml-connector/README.md, packages/dbml-core/README.md, packages/dbml-core/types/import/index.d.ts
- Add readme.md for dbml connector
- Fix broken link to the olde dbml core document page
- Fix type definition for dbml core
=> Update readme for dbml core and connector

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> Release v3.7.3

dbml-homepage/docs/docs.md, packages/dbml-core/src/model_structure/tableGroup.js, packages/dbml-core/types/model_structure/tableGroup.d.ts, packages/dbml-parse/src/lib/analyzer/validator/elementValidators/tableGroup.ts, packages/dbml-parse/src/lib/interpreter/elementInterpreter/tableGroup.ts, packages/dbml-parse/src/lib/interpreter/types.ts, packages/dbml-parse/src/services/suggestions/provider.ts, packages/dbml-parse/tests/interpreter/input/table_group_settings.in.dbml, packages/dbml-parse/tests/interpreter/output/table_group_settings.out.json, packages/dbml-parse/tests/validator/input/table_group_settings.in.dbml, packages/dbml-parse/tests/validator/output/table_group_settings.out.json
* Add syntax support for colors for Table Groups (validator & interpreter)
* Add suggestions for colors for Table Groups
* Update test cases
=> Support colors for Table Groups

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
- Support table group color syntax
=> Release v3.7.4

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
- Support BigQuery and Snowflake connector
-  Fix document page example
=> Release v3.8.0

dbml-homepage/docs/cli.md, dbml-homepage/docs/docs.md, dbml-homepage/docs/js-module/connector.md, dbml-homepage/docs/js-module/core.md
- Update document for BigQuery and snowflake connector
=> Docs - Update doc for bigquery and snowflake connector

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> Release v3.8.1

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
- Fix mssql connector issue: Missing data type size for numeric-based and string-based columns 
https://github.com/holistics/dbml/issues/644
=> Release v3.9.1

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump packages version to v3.9.2
=> Release v3.9.2

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> Release v3.9.3

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
- Release v3.4.0
https://github.com/holistics/dbml/issues/659
=> Release v3.9.4

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
- Fix many security issues
- Update type definition for Parser.js
- Upgrade docusaurus to v3.6.3
=> Release v3.9.5

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> Release v3.9.6

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> chores: update changelog

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> Release v3.11.0

yarn.lock
- Update missing deps for `yocto-queue`
=> chores: update missing deps yocto-queue

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
Release v3.13.1
https://github.com/holistics/dbml/issues/712
=> Release v3.13.1

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
- connector: Fix missing table description on mssql
https://github.com/holistics/dbml/pull/657
=> Release v3.13.2

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
* Bump packages version to v3.13.4
=> Release v3.13.4

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> Release v3.13.5

README.md, dbml-homepage/docs/home.md
- Added Scafoldr to the community contributions section of both README.md and dbml-homepage/docs/home.md.
- Scafoldr is a DBML-to-code generator that supports Node.js (Express + Sequelize), Java (Spring) and is expanding to more frameworks.
- The project is currently a work in progress, but a public open-source release is planned soon.
- Live preview available at: https://scafoldr.com/code-generator
1. Paste your DBML code into the editor (or use the provided example).
2. Click the "Get your code" button.
3. A modal will open – enter your project name and choose your preferred backend.
4. Enjoy your generated code! You can preview it directly or download everything as a zip.
#731
=> Docs: Add Scafoldr to Community Contributions

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> Release v3.13.8

CHANGELOG.md, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
=> Release version 3.13.9

dbml-homepage/docs/cli.md, packages/dbml-cli/src/cli/index.js
- Update bigquery connector cli description on homepage
=> misc: update bigquery connector cli description on homepage

CHANGELOG.md, dbml-playground/package.json, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json, yarn.lock
=> Release v3.14.0

CHANGELOG.md, dbml-playground/package.json, lerna.json, packages/dbml-cli/package.json, packages/dbml-connector/package.json, packages/dbml-core/package.json, packages/dbml-parse/package.json
- Release v3.14.1 contains the fix for Oracle exported for this issue:https://github.com/holistics/dbml/issues/756
=> Release v3.14.1

dbml-playground/package.json, yarn.lock
* Bump vite for dbml-playground to latest to fixes security issues
* https://github.com/holistics/dbml/security/dependabot/483
* https://github.com/holistics/dbml/security/dependabot/482
=> DBX-6342 misc: bump vite to v7.1.7 dbml-playground
