holistics/dbml

packages/dbml-core/src/parse/dbml/parser.pegjs

- Community Issue: [Cannot make one-to-one relationship. Underscore isn’t recognized](https://community.dbdiagram.io/t/cannot-make-one-to-one-relationship-underscore-isnt-recognized/275)
- After investigation, it turns out that the `dbml` parser has a mistake in description of relationship.
- Community Issue: [Cannot make one-to-one relationship. Underscore isn’t recognized](https://community.dbdiagram.io/t/cannot-make-one-to-one-relationship-underscore-isnt-recognized/275)
- Asana: [Wrong message of relationship between table](https://app.asana.com/0/1125458388096768/1138140611188609/f)

Fix relationship description

---

CONTRIBUTING.md

* Updated the CONTRIBUTING.md file to state that yarn must be installed, and updated procedure
none
none

fixes contributing setup section : yarn must be present to run 'lerna bootstrap'

---

packages/dbml-core/__tests__/exporter/postgres_exporter/input/general_schema.in.dbml
packages/dbml-core/__tests__/exporter/postgres_exporter/output/general_schema.out.sql
packages/dbml-core/src/export/PostgresExporter.js

* if the column is "bigint" with increment, then the exported column will be `BIGSERIAL` instead of `SERIAL` 
#85 : PostgreSql export -- bigint autoincrement should give bigserial instead of serial
NONE

fixes #85 : PostgreSql export -- bigint autoincrement should give bigserial instead of serial

---

packages/dbml-core/__tests__/parser/mssql-parse/input/inline_referential_actions.in.sql
packages/dbml-core/__tests__/parser/mssql-parse/input/table_constraints_indexes.in.sql
packages/dbml-core/__tests__/parser/mssql-parse/output/inline_referential_actions.out.json
packages/dbml-core/__tests__/parser/mssql-parse/output/table_constraints_indexes.out.json
packages/dbml-core/package.json
packages/dbml-core/src/model_structure/endpoint.js
packages/dbml-core/src/parse/mssql/fk_definition/actions.js
packages/dbml-core/src/parse/mssql/fk_definition/index.js
packages/dbml-core/src/parse/mssql/statements/statement_types/create_table/actions.js

- Fix error handling when endpoint have fields that are not in endpoint's table.
- Add support for implicit foreign key reference for mssql, only when columns on both sides have the same name, example:
`[user_id] int CONSTRAINT fk_order_user FOREIGN KEY REFERENCES [users]`
- Remove  setField in endpoint and move it to setFields, change field.name to fieldName in error message.

Fix endpoint error handling and support for implicit foreign key reference for mssql

---

packages/dbml-core/src/parse/mysql/parser.pegjs
packages/dbml-core/src/parse/mysqlParser.js

This is valid in mysql
```sql
create table products (
id int,
name varchar(255),
weight_measurement ENUM('lb', 'kg', '%'),
primary key(`id`)
) engine=innodb default charset=utf8;
```
From dbdiagram mysql import
The enhancement
* Add supported symbol to 'ExpChar'

[Enhancement]support symbol for mysql importer

---

README.md
dbml-homepage/docs/home/README.md

Hello!
As discussed in https://github.com/holistics/dbml/issues/154, this PR adds a link to [dbml-renderer](https://github.com/softwaretechnik-berlin/dbml-renderer) in both the project's `README.md` and the homepage.
Thank you for your help and support!

Add links to dbml-renderer

---

dbml-homepage/docs/docs/README.md
packages/dbml-core/__tests__/importer/mysql_importer/input/general_schema.in.sql
packages/dbml-core/__tests__/importer/mysql_importer/output/general_schema.out.dbml
packages/dbml-core/__tests__/importer/postgres_importer/input/general_schema.in.sql
packages/dbml-core/__tests__/importer/postgres_importer/output/general_schema.out.dbml
packages/dbml-core/__tests__/parser/postgres-parse/input/cmd_create_table.in.sql
packages/dbml-core/__tests__/parser/postgres-parse/output/cmd_create_table.out.json
packages/dbml-core/src/export/DbmlExporter.js
packages/dbml-core/src/parse/mssql/keyword_parsers.js
packages/dbml-core/src/parse/mysql/parser.pegjs
packages/dbml-core/src/parse/mysqlParser.js
packages/dbml-core/src/parse/postgresParser.js
packages/dbml-core/src/parse/postgresql/Base_rules.pegjs

* Add support for postgress array
* Fix mysql importer bugs
* https://github.com/holistics/dbml/issues/174
* https://github.com/holistics/dbml/issues/167
* https://github.com/holistics/dbml/issues/159
* https://github.com/holistics/dbml/issues/142
* Type name with square brackets when import to dbml now properly put inside double quotes.
* Remove duplicate KeywordDrop in mssql parser.
* Allow optional space after <USING> <HASH/BTREE> in mysql parser.
* Fix mysql composite foreign key bug: endpoints[0] of composite references now properly include all field (before, it only use the first field).

Dbml core/support postgres array and fix mysql bugs

---

dbml-homepage/docs/cli/README.md
packages/dbml-cli/__test__/sql2dbml/filename --mssql --out-file/expect-out-files/schema.dbml
packages/dbml-cli/__test__/sql2dbml/filename --mssql --out-file/in-files/schema.sql
packages/dbml-cli/__test__/sql2dbml/filename --mssql --out-file/options.json
packages/dbml-cli/__test__/sql2dbml/filename --mssql --out-file/stdout.txt
packages/dbml-cli/src/cli/index.js

* Add mssql importer to cli options (usage: sql2dbml --mssql <input_file_path>)
* https://github.com/holistics/dbml/issues/208

Add --mssql option for sql2dbml CLI

---

dbml-homepage/docs/docs/README.md
packages/dbml-cli/yarn.lock
packages/dbml-core/__tests__/exporter/mssql_exporter/input/many_to_many_relationship.in.dbml
packages/dbml-core/__tests__/exporter/mssql_exporter/output/many_to_many_relationship.out.sql
packages/dbml-core/__tests__/exporter/mysql_exporter/input/many_to_many_relationship.in.dbml
packages/dbml-core/__tests__/exporter/mysql_exporter/output/many_to_many_relationship.out.sql
packages/dbml-core/__tests__/exporter/postgres_exporter/input/many_to_many_relationship.in.dbml
packages/dbml-core/__tests__/exporter/postgres_exporter/output/many_to_many_relationship.out.sql
packages/dbml-core/src/export/MysqlExporter.js
packages/dbml-core/src/export/PostgresExporter.js
packages/dbml-core/src/export/SqlServerExporter.js
packages/dbml-core/src/export/utils.js
packages/dbml-core/src/parse/dbml/parser.pegjs
packages/dbml-core/src/parse/dbmlParser.js

* Implement parser for many to many relationship
* Implement export for many to many relationship
(https://github.com/holistics/dbml/issues/146#issuecomment-739096912)
* Add syntax `<>` for ref in parser.pegjs
* Add function `getRelations(operator)` to get relation for every operator relation in parser.pegjs
* Add function `buildJunctionFields1` to get fields that will the primary key of table first in PosgresExporter, MySqlExporter, SQLServerExporter
* Add function `buildJunctionFields2` to get fields that will the primary key of table second, if fields exist, it wils generate new name  in PosgresExporter, MySqlExporter, SQLServerExporter
* Add function `buildNewTableName` to create name for new table in PosgresExporter, MySqlExporter, SQLServerExporter
*  Add function …

Support many to many relationship

---

packages/dbml-core/__tests__/exporter/mssql_exporter/output/many_to_many_relationship.out.sql
packages/dbml-core/__tests__/exporter/mysql_exporter/output/many_to_many_relationship.out.sql
packages/dbml-core/__tests__/exporter/postgres_exporter/output/many_to_many_relationship.out.sql
packages/dbml-core/src/export/MysqlExporter.js
packages/dbml-core/src/export/PostgresExporter.js
packages/dbml-core/src/export/SqlServerExporter.js
packages/dbml-core/src/parse/dbmlParser.js

* Refactor exporter for MSSQL. MySQL, PostgreSQL
* Update parser for many to many
* Removed `buildIndexManytoMany` in SQLServerExporter, MySqlExporter, PostgresSQLExporter
* Build new parser for dbml
* Removed `usedIndexNames` in exportRef 
* Removed NOT NULL in `buildTableManyToMany`

Refactor exporter DBML to SQL with case many to many relationship

---

packages/dbml-core/__tests__/exporter/postgres_exporter/input/smallserial_type.in.dbml
packages/dbml-core/__tests__/exporter/postgres_exporter/output/smallserial_type.out.sql
packages/dbml-core/src/export/PostgresExporter.js

* Added SMALLSERIAL type when using increments in settings to export postgress sql
[(issue link here)](https://community.dbdiagram.io/t/wrong-postgres-smallserial-export/1450)
* Updated `function getFieldLines` to add type for increment
* Added `smallserial_type.in.dbml and smallserial_type.out.sql`  in test/export/postgresql  to test for smallserial type

Update type smallserial for increment

---

packages/dbml-core/__tests__/exporter/mssql_exporter/input/many_to_many_relationship.in.dbml
packages/dbml-core/__tests__/exporter/mssql_exporter/output/many_to_many_relationship.out.sql
packages/dbml-core/__tests__/exporter/mysql_exporter/input/many_to_many_relationship.in.dbml
packages/dbml-core/__tests__/exporter/mysql_exporter/output/many_to_many_relationship.out.sql
packages/dbml-core/__tests__/exporter/postgres_exporter/input/many_to_many_relationship.in.dbml
packages/dbml-core/__tests__/exporter/postgres_exporter/output/many_to_many_relationship.out.sql
packages/dbml-core/src/export/MysqlExporter.js
packages/dbml-core/src/export/PostgresExporter.js
packages/dbml-core/src/export/SqlServerExporter.js

* Add  schema name for the junction table:
```
Ref schema.table1.column1 <> schema.table2.column2 → will create a junction table: "schema"."table1_table2"
Ref schema1.table1.column1 <> schema2.table2.column2 → will create a junction table "schema1"."table1_table2"
```
([issue link here](https://community.dbdiagram.io/t/bug-many-to-many-references-not-honouring-schema-syntax/1539/3))
* Add schema name for `buildTableManyToMany`
* Add schema name for `buildForeignKeyManyToMany`
* Add new test for many to many relationships

Add schema name for the junction table of many-to-many relationship

---

packages/dbml-core/__tests__/importer/mysql_importer/input/on_update_current_timestamp.in.sql
packages/dbml-core/__tests__/importer/mysql_importer/output/on_update_current_timestamp.out.dbml
packages/dbml-core/src/parse/mysql/parser.pegjs
packages/dbml-core/src/parse/mysqlParser.js

* Ignore syntax ON UPDATE in fieldSettings
https://github.com/holistics/dbml/issues/279
https://github.com/holistics/dbml/issues/272
https://github.com/holistics/dbml/issues/141
https://github.com/holistics/dbml/issues/217
https://github.com/holistics/dbml/issues/237#issuecomment-1078768726
* Added  grammar ` / _ "ON"i _ "UPDATE"i _ type { return "not_supported" }`  in fieldSettings in MySQL parser.

Ignore on update current timestamp in mysql

---

packages/dbml-core/__tests__/exporter/mysql_exporter/input/multiple_schema.in.dbml
packages/dbml-core/__tests__/exporter/mysql_exporter/output/multiple_schema.out.sql
packages/dbml-core/src/export/MysqlExporter.js

The table comments DDL did not contain the schema name.
Added rendering of schema name, same way as it is done for other "alter table" commands.
Has not been reported as an issue yet.
None.

Rendering schema name for table comments

---

.github/workflows/test.yml

* Remove redundant `yarn build` step
- Remove `yarn build` step in CI test workflow:
- Reason: `yarn bootstrap` step will run `npm run prepublish` in all workspace packages which mean it will run `npm run build` too
- Lerna bootstrap docs: https://github.com/lerna/lerna/blob/main/libs/commands/bootstrap/README.md
- Result from CI job: https://github.com/holistics/dbml/actions/runs/4530731973/jobs/7980029303
- `@dbml/core` runs build in bootstrap step:
- `@dbml/cli` runs build in bootstrap step:
Please check directly on the box once each of these is done

Remove redundant build step

---

package.json
packages/dbml-cli/package.json
packages/dbml-cli/yarn.lock
packages/dbml-core/jestHelpers.js
packages/dbml-core/package.json
packages/dbml-core/yarn.lock
yarn.lock

- Bump jest and babel-jest to the latest version to fix security issues
- Migrate jest-raw-loader to @glen/jest-raw-loader
- Remove expect and coveralls packages
Fix security issues related to babel-jest@24.9.0 and jest@24.9.0:
- https://github.com/holistics/dbml/security/dependabot/2
- https://github.com/holistics/dbml/security/dependabot/190
- https://github.com/holistics/dbml/security/dependabot/219
- https://github.com/holistics/dbml/security/dependabot/262
- https://github.com/holistics/dbml/security/dependabot/335
- Remove unused `coveralls` package
- Remove `expect` package, use global `expect` from `jest` instead
- Bump `babel-jest` and `jest` to `v29.5.0`
- Migrate `jest-raw-loader` to `@glen/jest-raw-loader` due to a breaking change in Jest version 28: …

Bump jest and babel-jest to v29.5.0

---

package.json
packages/dbml-cli/package.json
packages/dbml-cli/yarn.lock
packages/dbml-core/package.json
packages/dbml-core/yarn.lock
yarn.lock

* Bump babel packages to the latest version to fix some security issues:
* @dbml/cli: @babel/cli@7.6.2, @babel/node@7.6.2
* https://github.com/holistics/dbml/security/dependabot/335
* @dbml/cli: @babel/cli@7.6.2:
* https://github.com/holistics/dbml/security/dependabot/2 
* https://github.com/holistics/dbml/security/dependabot/91
* https://github.com/holistics/dbml/security/dependabot/108
* https://github.com/holistics/dbml/security/dependabot/246
* https://github.com/holistics/dbml/security/dependabot/247
* https://github.com/holistics/dbml/security/dependabot/258
* https://github.com/holistics/dbml/security/dependabot/259
- Root:
- bump `@babel/core`, `@babel/plugin-transform-runtime` and `@babel/preset-env` to v7.21.4
- @dbml/cli:
- bump `@babel/cli` to v7.21.0
- bump …

Bump babel packages to the latest version

---

packages/dbml-cli/yarn.lock

* Bump eslint to 6.8.0 and mkdirp to 0.5.6 to fix a critical security issue: https://github.com/holistics/dbml/security/dependabot/335
- Bump `eslint` from version 6.4.0 to 6.8.0
- Bump `mkdirp` from version 0.5.1 to 0.5.6

Bump eslint to 6.8.0 and mkdirp to 0.5.6

---

dbml-homepage/yarn.lock

Bump packages to fix security issues:
- bump ansi-regex from 3.0.0 to 3.0.1: https://github.com/holistics/dbml/security/dependabot/251
- bump ansi-regex from 4.1.0 to 4.1.1: https://github.com/holistics/dbml/security/dependabot/250
- bump jsprim from 1.4.1 to 1.4.2: https://github.com/holistics/dbml/security/dependabot/195
- bump loader-utils from 1.2.3 to 1.4.2: https://github.com/holistics/dbml/security/dependabot/301
- bump minimist from 1.2.0 to 1.2.8: https://github.com/holistics/dbml/security/dependabot/336
Please check directly …

Bump ansi-regex, jsprim, loader-utils and minimist to fix security issues

---

dbml-homepage/yarn.lock

* Bump webpack-dev-server from 3.9.0 to 3.11.3 to fix https://github.com/holistics/dbml/security/dependabot/220

Bump webpack-dev-server from 3.9.0 to 3.11.3 in /dbml-homepage

---

dbml-homepage/yarn.lock

Bump packages to fix security issues:
- Fix https://github.com/holistics/dbml/security/dependabot/333:
- bump express from 4.17.1 to 4.18.2
- Fix https://github.com/holistics/dbml/security/dependabot/3:
- bump kind-of from 6.0.2 to 6.0.3
- Fix https://github.com/holistics/dbml/security/dependabot/21:
- bump copy-webpack-plugin from 5.0.4 to 5.1.2
- bump terser-webpack-plugin from 1.4.1 to 1.4.5
- bump vue-server-renderer from 2.6.10 to 2.7.14
- bump vue from 2.6.10 to 2.7.14
- bump vue-template-compiler from 2.6.10 to 2.7.14
Please …

Bump express, kind-of, vue and webpack plugins in /dbml-homepage

---

dbml-homepage/package.json
dbml-homepage/yarn.lock

* Force loader-utils from 0.2.17 to 1.4.2 to fix a critical issue https://github.com/holistics/dbml/security/dependabot/301
* `parseQuery` method was removed in 1.0.0 but added in 1.1.0, see [changelog](https://github.com/webpack/loader-utils/blob/master/CHANGELOG.md)
* Bump json5 ([changelog](https://github.com/json5/json5/blob/main/CHANGELOG.md)):
* 1.0.1 to 1.0.2: fix part of https://github.com/holistics/dbml/security/dependabot/334
* 2.1.1 to 2.2.3: fix https://github.com/holistics/dbml/security/dependabot/327
Please check directly …

Force loader-utils to 1.4.2 and bump json5

---

dbml-homepage/package.json
dbml-homepage/yarn.lock

* Force selfsigned ([changelog](https://github.com/jfromaniello/selfsigned/compare/v1.10.14...v2.1.1
)) to 2.1.1 to bump node-forge to 1.3.1 to fix 2 security issues:
* https://github.com/holistics/dbml/security/dependabot/223
* https://github.com/holistics/dbml/security/dependabot/221
* Bump postcss-svgo from 4.0.2 to 4.0.3 to fix https://github.com/holistics/dbml/security/dependabot/56

Force selfsigned to 2.1.1, bump postcss-svgo to 4.0.3 in /dbml-homepage

---

dbml-homepage/package.json
dbml-homepage/yarn.lock

- Bump vuepress and related packages to v1.9.9:
- fix json5 issue caused by older version of vuepress https://github.com/holistics/dbml/security/dependabot/334
- Remove unused vuepress plugins: can check if a plugin is used by checking the `plugins` option of https://github.com/holistics/dbml/blob/fa14082f8b281f65be0f7ed1f372cb42a8de8670/dbml-homepage/docs/.vuepress/config.js

Bump vuepress to 1.9.9 in /dbml-homepage 

---

dbml-homepage/package.json
dbml-homepage/yarn.lock

* Force glob-parent from 3.1.0 to 5.1.2 to fix https://github.com/holistics/dbml/security/dependabot/92
* [Changelog](https://github.com/gulpjs/glob-parent/blob/main/CHANGELOG.md#400-2021-01-27): v4 only has a breaking change related to "question marks" issue in Windows

Force glob-parent to 5.1.2 in /dbml-homepage

---

dbml-homepage/package.json
dbml-homepage/yarn.lock

Fix https://github.com/holistics/dbml/security/dependabot/146:
* Bump renderkid to 2.0.7 to bump css-select to 4.1.3
* Force optimize-css-assets-webpack-plugin from 5.0.3 to 6.0.1 to bump css-select to 4.1.3:
* Changelog: https://github.com/NMFR/optimize-css-assets-webpack-plugin/compare/v5.0.8...v6.0.0: v6 only adds internal method `getDefaultProcessor` and does not change any external APIs

Fix nth-check security issues in /dbml-homepage

---

README.md
dbml-homepage/deploy.sh
dbml-homepage/docs/docs/README.md
packages/dbml-cli/README.md
packages/dbml-cli/package.json
packages/dbml-core/README.md
packages/dbml-core/package.json

Update the dbml domain to https://dbml.dbdiagram.io
https://github.com/holistics/dbml/issues/353
- Update the dbml domain to https://dbml.dbdiagram.io
- Docs: Remove a broken link "Community Contributions"

Update dbml domain

---

packages/dbml-core/__tests__/importer/mssql_importer/input/default_parameters.in.sql
packages/dbml-core/__tests__/importer/mssql_importer/output/default_parameters.out.dbml
packages/dbml-core/src/parse/mssql/constraint_definition/index.js

Fix parsing of default values for MSSQL
#321 - sql2dbml -- mssql parsing for defaults
Changed MSSQL language definition to accept double-parenthesis around constant values (`DEFAULT ((0))`)

Fix default values for MS-SQL parser

---

dbml-homepage/docs/docs/README.md

* Modified the documentation to include an enum example that has a quoted name with spaces

Included enum example for names with spaces

---

.github/workflows/bearer.yml

Previous: scan when merge master
This PR: scan when [open, sync, reopen] a PR and only scan files changed

change(bearer_workflows): only scan pr diff

---

packages/dbml-core/src/parse/dbml/src/lib/serialization/serialize.ts

* Add a simple serializer as the later phases would cause the AST to have circular references, JSON.stringify by default would recurse infinitely.
* Previous PR: #414 
* Next PR: #420 

2. Simple Report serializer

---

packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/utils.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/types.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/utils.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/_preset_configs.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/custom.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/elementValidator.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/enum.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/indexes.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/note.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/project.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/ref.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/table.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/tableGroup.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/utils.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/types.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/utils.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/validator.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/validatorContext.ts

* Implement the validator for DBML parser
* Previous PR: #422
* Next PR: #424 
* Implementation details: [Notion](https://www.notion.so/holistics/Analyzer-4bc8949df2744e198f7d287141a5e738)

5. Parser base element validator

---

packages/dbml-core/src/parse/dbml/src/lib/analyzer/binder/binder.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/symbolIndex.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/symbolTable.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/symbols.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/symbol/utils.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/types.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/utils.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/elementValidator.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/indexes.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/ref.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/table.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/tableGroup.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/elementValidators/utils.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/types.ts
packages/dbml-core/src/parse/dbml/src/lib/analyzer/validator/utils.ts
packages/dbml-core/src/parse/dbml/src/lib/parser/nodes.ts
packages/dbml-core/src/parse/dbml/src/lib/serialization/serialize.ts

* Support serialization by using an id to refer to nodes and symbols in certain cases.
* This implementation is deprecated (see #432) as the id generators are global instances of singleton classes.
* Notable changes:
* `serialize.ts`
* nodes and symbols now accept ids in their constructors
* `NodeSymbolId` is now renamed to `NodeSymbolIndex` to reserve the name for Symbol id

7. add node & symbol ids to support proper serialization

---

packages/dbml-core/src/parse/dbml/src/compiler.ts
packages/dbml-core/src/parse/dbml/src/lib/lexer/lexer.ts
packages/dbml-core/src/parse/dbml/src/services/suggestions/utils.ts
packages/dbml-core/src/parse/dbml/tests/lexer/output/comment.out.json
packages/dbml-core/src/parse/dbml/tests/lexer/output/number.out.json
packages/dbml-core/src/parse/dbml/tests/parser/output/trailing_comments.out.json
packages/dbml-core/src/parse/dbml/tests/validator/output/complex_indexes.out.json
packages/dbml-core/src/parse/dbml/tests/validator/output/table_settings.out.json

* Single line comment was consuming newlines causing two separate lines with the first line containing a trailing comment be joined

Fix lexer single line comment

---

packages/dbml-core/src/parse/dbml/src/lib/parser/parser.ts

* Missing alias (`as` but no alias) in element header was not reported

fix: missing alias was not logged in parser

---

packages/dbml-core/src/parse/dbml/src/lib/interpreter/interpreter.ts
packages/dbml-core/src/parse/dbml/src/lib/interpreter/types.ts

* The interpreter currently yield aliases of kind 'Table' while the Database requires 'table'.
* Refine the type of alias's kind to avoid this in the future.

fix: bug in interpreter alias kind

---

packages/dbml-core/__tests__/importer/mysql_importer/input/lower_case.in.sql
packages/dbml-core/__tests__/importer/mysql_importer/output/lower_case.out.dbml
packages/dbml-core/src/parse/mysql/parser.pegjs
packages/dbml-core/src/parse/mysqlParser.js

Fix comment syntax in MySQL parser
- https://github.com/holistics/dbml/issues/450
- #461 
- MySQL parser: Ignore case-sensitive when parsing `COMMENT` token
- Add a new testcase to test lowercase SQLs

Fix comment syntax in MySQL parser

---

.github/workflows/bearer.yml

we have continue-on-error: true to always run reviewdog but this option not always work -> refactored flow with if: always()
Ref: https://github.com/Bearer/bearer/pull/1281

fix: bearer scan continue-on-error not works

---

packages/dbml-core/__tests__/model_exporter/dbml_exporter/input/comment_tables.in.json
packages/dbml-core/__tests__/model_exporter/dbml_exporter/output/comment_tables.out.dbml
packages/dbml-core/__tests__/model_exporter/mysql_exporter/input/comment_tables.in.json
packages/dbml-core/__tests__/model_exporter/mysql_exporter/output/comment_tables.out.sql
packages/dbml-core/__tests__/model_exporter/postgres_exporter/input/comment_tables.in.json
packages/dbml-core/__tests__/model_exporter/postgres_exporter/output/comment_tables.out.sql
packages/dbml-core/src/model_structure/database.js
packages/dbml-core/src/model_structure/enum.js
packages/dbml-core/src/model_structure/enumValue.js
packages/dbml-core/src/model_structure/field.js
packages/dbml-core/src/model_structure/schema.js
packages/dbml-core/src/model_structure/table.js

[https://github.com/holistics/dbml/issues/485](https://github.com/holistics/dbml/issues/485)

fix: type of note field that is string doesn show

---

packages/dbml-core/__tests__/importer/postgres_importer/output/db_dump.out.dbml
packages/dbml-core/src/export/DbmlExporter.js
packages/dbml-core/src/parse/ANTLR/ASTGeneration/postgres/PostgresASTGen.js

* Allow putting notes with simple quotes
https://github.com/holistics/dbml/issues/492
Simply escape simple quotes in notes to avolid dbml parsers to fail

fix(sql2dbml): properly escape notes when notes do contain some '

---

packages/dbml-parse/src/lib/analyzer/validator/elementValidators/table.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/enum.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/project.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
packages/dbml-parse/src/lib/interpreter/utils.ts
packages/dbml-parse/tests/interpreter/input/primary_key.in.dbml
packages/dbml-parse/tests/interpreter/output/index_tables.out.json
packages/dbml-parse/tests/interpreter/output/multiline_string.out.json
packages/dbml-parse/tests/interpreter/output/old_undocumented_syntax.out.json
packages/dbml-parse/tests/interpreter/output/primary_key.out.json
packages/dbml-parse/tests/interpreter/output/project.out.json
packages/dbml-parse/tests/old_tests/output/index_tables.out.json
packages/dbml-parse/tests/old_tests/output/multiline_string.out.json
packages/dbml-parse/tests/old_tests/output/project.out.json
packages/dbml-parse/tests/validator/input/duplicate_alias_name.in.dbml
packages/dbml-parse/tests/validator/output/alias_of_duplicated_names.out.json
packages/dbml-parse/tests/validator/output/duplicate_alias_name.out.json

* Fix error message when alias is a duplicate.
* Allow alias to be the same as the same table's name
* Interpret `primary key`
* No longer normalize note content, left as-is.
* Additional check in `TableValidator`.
* Additional logic in `TableInterpreter`.
* Remove `normalizeNoteContent`.
* Testcases for these.

Fix/dbml alias & primary key & note content bug

---

packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
packages/dbml-parse/src/services/suggestions/provider.ts

Fix the problems as pointed out in: https://holistics.slack.com/archives/C0278BDLPK8/p1706870126558909.
NO breaking change is introduced!
* Add the missing return after creating the new Report, make that line meaningless
* Add the check whether `container.name` is an instance of an `IdentifierStream` node, otherwise, there will be an uncaught error when it's actually a `PrimaryExpresssionNode`.
* Add the `any` assertion.

fix: type errors and missing return

---

packages/dbml-parse/src/lib/lexer/lexer.ts
packages/dbml-parse/tests/lexer/input/identifiers.in.dbml
packages/dbml-parse/tests/lexer/input/identifiers_starting_with_digits.in.dbml
packages/dbml-parse/tests/lexer/output/identifiers.out.json
packages/dbml-parse/tests/lexer/output/identifiers_starting_with_digits.out.json

* Identifiers like `234_abc` are now supported.
* Identifiers with digits only must be quoted.

fix: support identifiers starting with numbers

---

packages/dbml-parse/src/lib/interpreter/utils.ts
packages/dbml-parse/tests/interpreter/input/circular_ref_1_inline_1_element.in.dbml
packages/dbml-parse/tests/interpreter/input/circular_ref_2_elements.in.dbml
packages/dbml-parse/tests/interpreter/input/circular_ref_2_inlines.in.dbml
packages/dbml-parse/tests/interpreter/output/circular_ref_1_inline_1_element.out.json
packages/dbml-parse/tests/interpreter/output/circular_ref_2_elements.out.json
packages/dbml-parse/tests/interpreter/output/circular_ref_2_inlines.out.json

* Circular refs with one inline and one element can not be detected
* Example:
```
Table A {
id int [ref: > B.id]
}
Table B {
id int
}
Ref: A.id > B.id
```
* Fix a bug in the circular detection util

Fix circular ref

---

packages/dbml-parse/src/lib/analyzer/validator/elementValidators/enum.ts
packages/dbml-parse/src/lib/analyzer/validator/elementValidators/ref.ts
packages/dbml-parse/src/lib/parser/utils.ts
packages/dbml-parse/tests/validator/input/invalid_args.in.dbml
packages/dbml-parse/tests/validator/output/enum.out.json
packages/dbml-parse/tests/validator/output/invalid_args.out.json

* Fix the problem:
```
Enum Person {
id integer
}
```
go uncaught in the validator
* The old bug was because the optional setting list was not treated properly.
* Fix the error message of invalid enum field.
* Fix the uncaught error in this situation:
* `getMemberChain` takes `ArrayNode` into account
* Enum and Ref validator

Fix validate when redundant args & `getMemberChain`

---

packages/dbml-parse/src/lib/analyzer/validator/elementValidators/ref.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
packages/dbml-parse/src/services/suggestions/provider.ts
packages/dbml-parse/tests/binder/input/ref.in.dbml
packages/dbml-parse/tests/binder/output/ref.out.json
packages/dbml-parse/tests/interpreter/input/circular_ref_1_inline_1_element.in.dbml
packages/dbml-parse/tests/interpreter/output/circular_ref_1_inline_1_element.out.json
packages/dbml-parse/tests/validator/input/ref_in_table.in.dbml
packages/dbml-parse/tests/validator/output/ref_in_table.out.json

* This syntax (ref in table) is no longer supported:
```
Table A {
id integer
code integer
Ref: id > code
}
```
* Ref validator
* Table interpreter
* Element suggestion for table column (no longer suggest ref)

Remove ref in table syntax

---

packages/dbml-parse/src/lib/interpreter/elementInterpreter/ref.ts
packages/dbml-parse/src/lib/interpreter/types.ts
packages/dbml-parse/tests/interpreter/input/ref_settings.in.dbml
packages/dbml-parse/tests/interpreter/output/ref_settings.out.json
packages/dbml-parse/tests/interpreter/output/referential_actions.out.json
packages/dbml-parse/tests/old_tests/output/referential_actions.out.json

* This snippet does not get interpreted properly (unquoted delete and update value settings)
```
Ref: A.id > B.id [update: set default, delete: set null]
```

fix: unquoted update & delete ref setting

---

packages/dbml-core/__tests__/normalized_model/schema_def.out.json
packages/dbml-parse/src/lib/interpreter/elementInterpreter/enum.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/sticky_note.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
packages/dbml-parse/src/lib/interpreter/utils.ts
packages/dbml-parse/tests/interpreter/input/note_normalize.in.dbml
packages/dbml-parse/tests/interpreter/output/multiline_string.out.json
packages/dbml-parse/tests/interpreter/output/note_normalize.out.json
packages/dbml-parse/tests/interpreter/output/sticky_notes.out.json
packages/dbml-parse/tests/old_tests/output/multiline_string.out.json

* Add a note content normalization step to allow for more user-friendly markdown notes 

fix: add normalize note content

---

packages/dbml-parse/src/services/suggestions/provider.ts

* Fix this error:
https://github.com/user-attachments/assets/2487ff80-461d-445f-aabf-65d6e38963e1
* This is due to when the attribute name is blank and the cursor is currently after the colon, the autocompletion provider will try to unwrap the non existent attribute name (which is `None`) to get the suggestions for the attribute value.
* `suggestInAttribute` in completion provider: `unwrap_or` instead of `unwrap`

fix: safe unwrapping in suggesting attribute value when name is blank

---

.github/workflows/test.yml
package.json
packages/dbml-cli/package.json
packages/dbml-core/package.json

- Clean build cache before build process
- Config to require using node 18 or higher
- https://github.com/holistics/dbml/issues/607
- Add `clean-build` script in the root folder
- Add required engines

Fix - Clean build cache and required using node 18 or higher

---

dbml-homepage/docs/docs.md

* Add syntax manuals for table group notes.
* Re-arrange sections

Add syntax manuals for table group notes

---

bearer.yml
dbml-homepage/configs/sidebars.ts
dbml-homepage/docs/cli.md
dbml-homepage/docs/docs.md
dbml-homepage/docs/home.md
dbml-homepage/docs/js-module/connector.md
dbml-homepage/docs/js-module/core.md
dbml-homepage/docusaurus.config.ts
dbml-homepage/package.json
dbml-homepage/yarn.lock

Refactor js module document:
- Add connector and core pages
- Add plugin npm2yarn
- Config to show more level on TOC

Docs - Add document for connector

---

dbml-homepage/docs/docs.md
packages/dbml-core/types/model_structure/tableGroup.d.ts

* Change some example syntax from `e-commerce` to `e_commerce`
* Add missing property `color` for `TableGroup`'s type definition

Fix erroneous examples in document for Table Groups

---

packages/dbml-cli/src/cli/connector.js
packages/dbml-cli/src/cli/index.js
packages/dbml-cli/src/cli/utils.js
packages/dbml-connector/package.json
packages/dbml-connector/src/connectors/connector.ts
packages/dbml-connector/src/connectors/mssqlConnector.ts
packages/dbml-connector/src/connectors/postgresConnector.ts
packages/dbml-connector/src/connectors/snowflakeConnector.ts
packages/dbml-connector/src/connectors/types.ts
packages/dbml-connector/src/ddl_samples/snowflake.sql
packages/dbml-connector/src/utils/parseSchema.ts
packages/dbml-core/src/parse/databaseGenerator.js
yarn.lock

* Add Snowflake connector
* Add Snowflake connector
* Allow users to select schema when fetching schema information from: Postgresql, Mysql, MSSQL, and Snowflake.

Add Snowflake connector

---

packages/dbml-core/types/parse/Parser.d.ts

The Database.constructor parameter requires RawDatabase because the Database.export method executed by ModelExporter.export (format=json) returns a regular object instead of RawDatabase, which is different from RawDatabase. Therefore, when using Parser.parse(str, format=json), str must be in RawDatabase or its json form to alert everyone about unexpected errors caused by their differences.
The Database.constructor parameter requires RawDatabase 

Fix: When the parameter format is JSON in Parser.parse, the first parameter 'parse' must be RawDatabase

---

.eslintrc.json
packages/dbml-cli/__test__/db2dbml/postgres/expect-out-files/schema.dbml
packages/dbml-cli/__test__/db2dbml/postgres/schema.sql
packages/dbml-connector/__tests__/connector.test.ts
packages/dbml-connector/__tests__/connectors/postgres/expect-out-files/schema.json
packages/dbml-connector/src/connectors/mssqlConnector.ts
packages/dbml-connector/src/connectors/postgresConnector.ts

Fix postgres connector issues related to:
- Duplicated fields
- Failed to fetch enums if there is the same enum_type name in different schemas.
Fix wrong enums when fetching in mssql.
- Fix the eslintrc to parse ts file correctly
- Remove wrong enums when fetching in mssql
- Update the sql which fetching tables, fields, and comments to  avoid fetching duplicated fields
- Update the sql which fetching enums to support the same enum_type name in different schema_name

Fix postgres connector issues

---

packages/dbml-parse/package.json
packages/dbml-parse/tsconfig.json
packages/dbml-parse/vite.config.ts
yarn.lock

* Upgrade `vite-plugin-dts`, which resolves this [security issue](https://github.com/holistics/dbml/security/dependabot/413).
* Fix `tsconfig` to `include` all `src` not just the entry file, resolving [this issue](https://github.com/holistics/dbml/issues/631).
* Remove extraneous `vite-dts` (intended `vite-plugin-dts`)

chore/upgrade vite plugin dts & fix tsconfig to properly include all sources

---

packages/dbml-cli/__test__/db2dbml/mssql/expect-out-files/schema.dbml
packages/dbml-cli/__test__/db2dbml/mssql/schema.sql
packages/dbml-cli/__test__/db2dbml/mysql/expect-out-files/schema.dbml
packages/dbml-cli/__test__/db2dbml/mysql/schema.sql
packages/dbml-cli/__test__/db2dbml/postgres/expect-out-files/schema.dbml
packages/dbml-cli/__test__/db2dbml/postgres/schema.sql
packages/dbml-connector/__tests__/connectors/mssql/expect-out-files/schema.json
packages/dbml-connector/__tests__/connectors/mysql/expect-out-files/schema.json
packages/dbml-connector/__tests__/connectors/postgres/expect-out-files/schema.json

- Add more tests for dbml connector after fixing escape quote string

Connector - Fix escape note with special characters

---

packages/dbml-core/src/export/DbmlExporter.js

Model Exporter cannot export <> refs in dbml
* Support export <> refs when exporting dbml inside Model Exporter

Model Exporter cannot export <> refs in dbml

---

packages/dbml-cli/__test__/db2dbml/mssql/expect-out-files/schema.dbml
packages/dbml-cli/__test__/db2dbml/mssql/schema.sql
packages/dbml-connector/__tests__/connectors/mssql/expect-out-files/schema.json
packages/dbml-connector/src/connectors/mssqlConnector.ts

- Fetch numeric precision and scale for numeric-based column
- Fetch character max length for string-based column
https://github.com/holistics/dbml/issues/644

Fix mssql connector - Missing data type size for numeric-based and string-based columns

---

packages/dbml-cli/__test__/db2dbml/mssql/expect-out-files/schema.dbml
packages/dbml-cli/__test__/db2dbml/postgres/expect-out-files/schema.dbml
packages/dbml-connector/__tests__/connectors/mssql/expect-out-files/schema.json
packages/dbml-connector/__tests__/connectors/postgres/expect-out-files/schema.json
packages/dbml-connector/src/connectors/bigqueryConnector.ts
packages/dbml-connector/src/connectors/mssqlConnector.ts
packages/dbml-connector/src/connectors/postgresConnector.ts
packages/dbml-connector/src/connectors/snowflakeConnector.ts

Fix issue: The generated table from connectors cannot keep the ordinal position according to the SQL creation script.
- PostgreSQL: fixed function `generateTablesAndFields`
- Added CTE to get the table ordinal position using object id from[`pg_class` table](https://www.postgresql.org/docs/14/catalog-pg-class.html)
- Replaced `order by t.table_name` by `order by t.table_ordinal_position`
- MSSQL: fixed function `generateTablesFieldsAndEnums`
- Added `select t.create_date as table_create_date` and order by this field
- Added `select c.column_id as column_id` and order by this field
- MySQL: _cannot fix since there is no appropriate information_
- BigQuery: replaced `order by t.table_name` by `order by t.create_time` in `generateTablesAndFields` function
- Snowflake: replaced `order by …

Connector - Keep table ordinal position

---

packages/dbml-connector/src/connectors/bigqueryConnector.ts

* fixes https://github.com/holistics/dbml/issues/659. Please see https://cloud.google.com/bigquery/docs/information-schema-tables#schema (`creation_time` should be the right column name, not `create_time`)
https://github.com/holistics/dbml/issues/659
* fixed the column name used in BigQuery query.

fix: db2dbml bigquery connector's query

---

packages/dbml-core/types/index.d.ts
packages/dbml-core/types/parse/Parser.d.ts

Update type definition for Parser.js:
- Add missing `parseMySQLToJSONv2`, `parseDBMLToJSONv2` and `parseSnowflakeToJSON` methods
- Add type for `ParseFormat`
- Add the missing `DBMLCompiler` field

Update type definition for Parser.js

---

dbml-homepage/package.json
dbml-homepage/yarn.lock

- Upgrade Docusaurus to 3.6.3
- Fix path-to-regex issues.
- https://github.com/holistics/dbml/security/dependabot/427
-  https://github.com/holistics/dbml/security/dependabot/428

Homepage - Upgrade docusaurus to 3.6.3

---

packages/dbml-connector/src/connectors/postgresConnector.ts

This was likely a copy-paste mistake since the table `information_schema.tables t`
does exist in the next query but is missing from the current one.
This was causing:
```
error: missing FROM-clause entry for table "t"
at /usr/local/lib/node_modules/@dbml/cli/node_modules/pg/lib/client.js:535:17
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async generateTablesAndFields (/usr/local/lib/node_modules/@dbml/cli/node_modules/@dbml/connector/dist/connectors/postgresConnector.js:159:35)
at async Promise.all (index 0)
at async fetchSchemaJson (/usr/local/lib/node_modules/@dbml/cli/node_modules/@dbml/connector/dist/connectors/postgresConnector.js:420:17)
at async connectionHandler (/usr/local/lib/node_modules/@dbml/cli/lib/cli/connector.js:24:24)
```
when running …

Fix missing FROM-clause entry for table "t"

---

.github/workflows/test.yml
packages/dbml-core/__tests__/normalized_model/schema_def.out.json
packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
packages/dbml-parse/tests/interpreter/output/comment.out.json
packages/dbml-parse/tests/interpreter/output/default_tables.out.json
packages/dbml-parse/tests/interpreter/output/enum_tables.out.json
packages/dbml-parse/tests/interpreter/output/general_schema.out.json
packages/dbml-parse/tests/interpreter/output/index_tables.out.json
packages/dbml-parse/tests/interpreter/output/multi_notes.out.json
packages/dbml-parse/tests/interpreter/output/multiline_string.out.json
packages/dbml-parse/tests/interpreter/output/note_normalize.out.json
packages/dbml-parse/tests/interpreter/output/note_normalize_with_top_empty_lines.out.json
packages/dbml-parse/tests/interpreter/output/old_undocumented_syntax.out.json
packages/dbml-parse/tests/interpreter/output/primary_key.out.json
packages/dbml-parse/tests/interpreter/output/project.out.json
packages/dbml-parse/tests/interpreter/output/referential_actions.out.json
packages/dbml-parse/tests/interpreter/output/sticky_notes.out.json
packages/dbml-parse/tests/interpreter/output/table_group.out.json
packages/dbml-parse/tests/interpreter/output/table_group_element.out.json
packages/dbml-parse/tests/interpreter/output/table_group_settings.out.json
packages/dbml-parse/tests/interpreter/output/table_settings.out.json

Fix: Unset not_null if null or not_null setting is not specified
- Set `not_null` to `undefined` if neither `null` nor `not null` configuration is specified
- `not_null` will only have a boolean value if there is `null` or `not null` in the field setting

Fix: Unset not_null if null or not_null setting is not specified

---

packages/dbml-parse/src/lib/lexer/utils.ts
packages/dbml-parse/tests/parser/input/function_application.in.dbml
packages/dbml-parse/tests/parser/output/function_application.out.json

* Fix an issue where tab characters are not recognized as white-space characters (the character after `"id"` in the image is `\t`)

DBX-5750: Fix an issue where tab characters are not recognized as white-space characters

---

dbml-homepage/docs/docs.md
packages/dbml-core/__tests__/normalized_model/schema_def.in.dbml
packages/dbml-parse/src/lib/analyzer/binder/types.ts
packages/dbml-parse/src/lib/analyzer/validator/elementValidators/ref.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/ref.ts
packages/dbml-parse/tests/binder/input/ref_name_and_color_setting.in.dbml
packages/dbml-parse/tests/binder/output/ref_name_and_color_setting.out.json
packages/dbml-parse/tests/interpreter/input/ref_name_and_color_setting.in.dbml
packages/dbml-parse/tests/interpreter/output/ref_name_and_color_setting.out.json
packages/dbml-parse/tests/validator/input/ref_error_setting.in.dbml
packages/dbml-parse/tests/validator/input/ref_name_and_color_setting.in copy.dbml
packages/dbml-parse/tests/validator/output/ref_error_setting.out.json
packages/dbml-parse/tests/validator/output/ref_name_and_color_setting.out.json

* Revert some changes from https://github.com/holistics/dbml/pull/678
* Move Ref color setting validation from ElementDeclarationNode setting list to sub fields setting list. New ref's color setting syntax:
```
// Short form
Ref short_ref: b.id < c.id [color: #aabbcc]
// Long form
Ref long_ref {
c.id < b.c_id [color: #123456]
}
```

fix: Incorrect Ref color settings position

---

dbml-homepage/docs/docs.md

Fix the wrong double quote character in the public doc that is not recognized in the parser

Doc: fix wrong double quote character

---

packages/dbml-core/types/parse/Parser.d.ts

- Correct type of `Parser.parseDBMLToJSONv2`: `static parseDBMLToJSONv2(str: string, dbmlCompiler?: Compiler): RawDatabase;`
https://github.com/holistics/dbml/issues/685

fix: make dbml compiler can be undefined in parser.d.ts

---

.github/workflows/test.yml
packages/dbml-connector/src/connectors/mssqlConnector.ts

* Order table with same create_date by object_id instead of table create date in mssql connector
* Upgrade tests ci node version to 22

Fix flaky db2dbml/mssql test cause by inconsistent table ordering

---

packages/dbml-core/__tests__/parser/mssql-parse/input/default_tables.in.sql
packages/dbml-core/__tests__/parser/mssql-parse/input/wrapped_type.in.sql
packages/dbml-core/__tests__/parser/mssql-parse/output/default_tables.out.json
packages/dbml-core/__tests__/parser/mssql-parse/output/wrapped_type.out.json
packages/dbml-core/src/parse/ANTLR/ASTGeneration/mssql/MssqlASTGen.js

- Fix:
- Cannot parse varchar(max) like data type
- Cannot parse double precision
- Fix eslint for `MssqlASTGen`
https://github.com/holistics/dbml/issues/712

MSSQL: fix cannot parse varchar(max) and double precision

---

lerna.json
packages/dbml-cli/package.json
packages/dbml-connector/package.json
packages/dbml-core/__tests__/normalized_model/table_partial.in.dbml
packages/dbml-core/__tests__/normalized_model/table_partial.out.json
packages/dbml-core/package.json
packages/dbml-parse/package.json
packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/tablePartial.ts
packages/dbml-parse/src/lib/interpreter/utils.ts
packages/dbml-parse/tests/interpreter/input/index_table_partial.in.dbml
packages/dbml-parse/tests/interpreter/input/referential_actions.in.dbml
packages/dbml-parse/tests/interpreter/input/table_partial.in.dbml
packages/dbml-parse/tests/interpreter/output/index_table_partial.out.json
packages/dbml-parse/tests/interpreter/output/referential_actions.out.json
packages/dbml-parse/tests/interpreter/output/table_partial.out.json

* Fix TablePartial not handling column type that have arguments (fix DBX-5987)
* `function processColumnType` in TablePartial extracted the name from the original typeNode, which is `CallExpressionNode` for column type with arguments
* It should have extracted the callee of the call expression instead
* Fix ESLint for
* `interpreter/elementInterpreter/table.ts`
* `interpreter/elementInterpreter/tablePartial.ts`
* `interpreter/utils.ts`
* Moved `function processDefaultValue` and `function processColumnType` from `table.ts` and `tablePartial.ts` to `utils.ts` as those 2 files use the same helper functions

Fix not handling column type with arguments in TablePartial

---

dbml-homepage/yarn.lock

Fix vulnerability issues:
- https://github.com/holistics/dbml/security/dependabot/439
- https://github.com/holistics/dbml/security/dependabot/454
Bump express and prismjs versions in `yarn.lock`

DBX-6028 Bump express and prismjs to fix vulnerability issues

---

lerna.json
packages/dbml-cli/package.json
packages/dbml-connector/package.json
packages/dbml-core/package.json
packages/dbml-parse/package.json
packages/dbml-parse/src/lib/analyzer/binder/elementBinder/elementBinder.ts
packages/dbml-parse/src/lib/analyzer/utils.ts
packages/dbml-parse/src/lib/analyzer/validator/elementValidators/enum.ts
packages/dbml-parse/src/lib/analyzer/validator/elementValidators/indexes.ts
packages/dbml-parse/src/lib/analyzer/validator/elementValidators/note.ts
packages/dbml-parse/src/lib/analyzer/validator/elementValidators/project.ts
packages/dbml-parse/src/lib/analyzer/validator/elementValidators/ref.ts
packages/dbml-parse/src/lib/analyzer/validator/elementValidators/table.ts
packages/dbml-parse/src/lib/analyzer/validator/elementValidators/tableGroup.ts
packages/dbml-parse/src/lib/analyzer/validator/elementValidators/tablePartial.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/sticky_note.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/table.ts
packages/dbml-parse/src/lib/interpreter/elementInterpreter/tablePartial.ts
packages/dbml-parse/src/lib/interpreter/utils.ts
packages/dbml-parse/src/lib/parser/contextStack.ts
packages/dbml-parse/src/lib/parser/nodes.ts
packages/dbml-parse/src/lib/parser/parser.ts
packages/dbml-parse/src/lib/parser/utils.ts
packages/dbml-parse/vite.config.ts

- Remove `lodash-es` from build config to fix import issue related to `@dbml/parse` package for node versions lower than 22.12.0
- Update lodash import to have better tree shaking
- config(vite): Remove `lodash-es` from rollup's external config
- Update lodash's imports to only import required methods instead of the whole package to reduce bundle size

fix: remove `lodash-es` from external config and update lodash import to have better tree shaking

---

package.json
yarn.lock

* Fix https://github.com/holistics/dbml/security/dependabot/481

DBX-6258: bump tmp to v0.2.5 to fix security issues
